/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    landingPage: LandingPage;
    posts: Post;
    aboutPage: AboutPage;
    customers: Customer;
    families: Family;
    children: Child;
    child_documents: ChildDocument;
    audit_logs: AuditLog;
    notifications: Notification;
    'economy-transactions': EconomyTransaction;
    'bank-connections': BankConnection;
    'bank-transactions': BankTransaction;
    'bank-transfers': BankTransfer;
    'calendar-events': CalendarEvent;
    'economy-requests': EconomyRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    landingPage: LandingPageSelect<false> | LandingPageSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    aboutPage: AboutPageSelect<false> | AboutPageSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    families: FamiliesSelect<false> | FamiliesSelect<true>;
    children: ChildrenSelect<false> | ChildrenSelect<true>;
    child_documents: ChildDocumentsSelect<false> | ChildDocumentsSelect<true>;
    audit_logs: AuditLogsSelect<false> | AuditLogsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'economy-transactions': EconomyTransactionsSelect<false> | EconomyTransactionsSelect<true>;
    'bank-connections': BankConnectionsSelect<false> | BankConnectionsSelect<true>;
    'bank-transactions': BankTransactionsSelect<false> | BankTransactionsSelect<true>;
    'bank-transfers': BankTransfersSelect<false> | BankTransfersSelect<true>;
    'calendar-events': CalendarEventsSelect<false> | CalendarEventsSelect<true>;
    'economy-requests': EconomyRequestsSelect<false> | EconomyRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landingPage".
 */
export interface LandingPage {
  id: number;
  /**
   * Internal title for admin reference
   */
  title: string;
  hero: {
    title: string;
    subtitle: string;
    description: string;
    image?: (number | null) | Media;
    primaryCTA: {
      label: string;
      url: string;
    };
    secondaryCTA?: {
      label?: string | null;
      url?: string | null;
    };
  };
  about: {
    title: string;
    content: string;
    utfordringer?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    prinsipper?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  howItWorks: {
    title: string;
    steps?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  features: {
    title: string;
    intro?: string | null;
    image?: (number | null) | Media;
    items?:
      | {
          featureTitle: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  whySamsam: {
    title: string;
    description: string;
    image?: (number | null) | Media;
    reasons?:
      | {
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  faq: {
    title: string;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  finalCTA: {
    title: string;
    description: string;
    primaryButton: {
      label: string;
      url: string;
    };
    secondaryButton?: {
      label?: string | null;
      url?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  family: number | Family;
  author: number | Customer;
  authorName: string;
  type: 'general' | 'child-update';
  child?: (number | null) | Child;
  title?: string | null;
  content: string;
  important?: boolean | null;
  attachments?: (number | Media)[] | null;
  likes?: (number | Customer)[] | null;
  comments?:
    | {
        author: number | Customer;
        authorName: string;
        content: string;
        createdAt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "families".
 */
export interface Family {
  id: number;
  name?: string | null;
  inviteCode: string;
  members: (number | Customer)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  firstName: string;
  lastName: string;
  birthDate: string;
  phone: string;
  address: string;
  gender: 'male' | 'female' | 'other';
  familyRole: 'father' | 'mother' | 'sibling' | 'other';
  avatar?: (number | null) | Media;
  family?: (number | null) | Family;
  language?: ('no' | 'en') | null;
  notificationsEnabled?: boolean | null;
  notifyCalendarChanges?: boolean | null;
  notifyExpenseUpdates?: boolean | null;
  notifyStatusUpdates?: boolean | null;
  notifyDocumentUpdates?: boolean | null;
  sharePhoneWithFamily?: boolean | null;
  shareAddressWithFamily?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "children".
 */
export interface Child {
  id: number;
  family: number | Family;
  fullName: string;
  birthDate: string;
  gender?: ('na' | 'male' | 'female' | 'other') | null;
  /**
   * Upload an image (JPG/PNG).
   */
  avatar?: (number | null) | Media;
  nationalId?: string | null;
  medical?: {
    bloodType?: ('unknown' | 'A' | 'B' | 'AB' | 'O' | 'A+' | 'A-' | 'B+' | 'B-' | 'AB+' | 'AB-' | 'O+' | 'O-') | null;
    allergies?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    conditions?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    notesShort?: string | null;
    gp?: {
      name?: string | null;
      clinic?: string | null;
      phones?:
        | {
            value: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  school?: {
    schoolName?: string | null;
    className?: string | null;
    mainTeacher?: string | null;
  };
  emergencyContacts?:
    | {
        name: string;
        relation?: ('mother' | 'father' | 'grandparent' | 'guardian' | 'babysitter' | 'relative' | 'other') | null;
        isPrimary?: boolean | null;
        phones?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  profileStatus: 'active' | 'inactive' | 'archived';
  /**
   * Optional reason when setting profile inactive or archived.
   */
  profileStatusReason?: string | null;
  profileStatusChangedBy?: (number | null) | Customer;
  profileStatusChangedAt?: string | null;
  status: 'pending' | 'confirmed';
  createdBy?: (number | null) | Customer;
  lastEditedBy?: (number | null) | Customer;
  confirmedBy?: (number | null) | Customer;
  confirmedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage".
 */
export interface AboutPage {
  id: number;
  title: string;
  hero: {
    title: string;
    subtitle: string;
    image?: (number | null) | Media;
  };
  intro: {
    title: string;
    content: string;
  };
  missionVision: {
    missionTitle: string;
    missionText: string;
    visionTitle: string;
    visionText: string;
  };
  values: {
    title: string;
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  story: {
    title: string;
    content: string;
  };
  commitment: {
    title: string;
    items?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  cta: {
    title: string;
    text: string;
    button: {
      label: string;
      url: string;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "child_documents".
 */
export interface ChildDocument {
  id: number;
  family: number | Family;
  child: number | Child;
  file: number | Media;
  title: string;
  category: 'agreement' | 'school' | 'health' | 'id' | 'other';
  noteShort?: string | null;
  uploadedBy: number | Customer;
  uploadedByName?: string | null;
  version: number;
  /**
   * If this document replaces an older one, link it here.
   */
  replaces?: (number | null) | ChildDocument;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit_logs".
 */
export interface AuditLog {
  id: number;
  family: number | Family;
  child?: (number | null) | Child;
  childNameSnapshot?: string | null;
  actorId?: string | null;
  actorType: 'customer' | 'admin' | 'system';
  actorRole?: ('mother' | 'father' | 'parent' | 'admin' | 'system') | null;
  relatedToRole?: ('mother' | 'father' | 'both' | 'child' | 'system') | null;
  actorName?: string | null;
  action: string;
  entityType: 'child' | 'document' | 'event' | 'post' | 'economy' | 'confirmation' | 'other';
  scope?: ('calendar' | 'economy' | 'documents' | 'child_profile' | 'confirmation' | 'system' | 'other') | null;
  severity?: ('info' | 'important' | 'critical') | null;
  visibleInFamilyTimeline?: boolean | null;
  entityId?: string | null;
  targetLabel?: string | null;
  summary?: string | null;
  changes?:
    | {
        field: string;
        from?: string | null;
        to?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  recipient: number | Customer;
  family?: (number | null) | Family;
  child?: (number | null) | Child;
  type: 'calendar' | 'expense' | 'request' | 'bank' | 'status' | 'documents' | 'post';
  event:
    | 'created'
    | 'updated'
    | 'deleted'
    | 'confirmed'
    | 'declined'
    | 'commented'
    | 'liked'
    | 'uploaded'
    | 'replaced'
    | 'approved'
    | 'rejected'
    | 'paid';
  title: string;
  message?: string | null;
  link?: string | null;
  isRead?: boolean | null;
  readAt?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "economy-transactions".
 */
export interface EconomyTransaction {
  id: number;
  family: number | Family;
  createdBy: number | Customer;
  paidBy: number | Customer;
  child?: (number | null) | Child;
  title: string;
  description?: string | null;
  type: 'expense' | 'income';
  category:
    | 'food'
    | 'housing'
    | 'transport'
    | 'health'
    | 'school'
    | 'activities'
    | 'clothes'
    | 'bills'
    | 'salary'
    | 'other';
  amount: number;
  currency: string;
  status: 'paid' | 'pending';
  transactionDate: string;
  sourceType?: ('payment' | 'request') | null;
  requestRef?: (number | null) | EconomyRequest;
  requestCreatedByName?: string | null;
  approvedByName?: string | null;
  paidFromScope?: ('family' | 'personal') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "economy-requests".
 */
export interface EconomyRequest {
  id: number;
  family: number | Family;
  createdBy: number | Customer;
  createdByName: string;
  child?: (number | null) | Child;
  title: string;
  amount: number;
  category: 'food' | 'housing' | 'transport' | 'health' | 'school' | 'activities' | 'clothes' | 'bills' | 'other';
  notes?: string | null;
  status: 'pending' | 'approved' | 'rejected';
  reviewedBy?: (number | null) | Customer;
  reviewedAt?: string | null;
  decisionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bank-connections".
 */
export interface BankConnection {
  id: number;
  family: number | Family;
  connectionScope: 'family' | 'personal';
  ownerCustomer?: (number | null) | Customer;
  provider: 'enable-banking' | 'neonomics';
  status: 'pending' | 'connected' | 'expired' | 'failed';
  state?: string | null;
  externalSessionId?: string | null;
  externalAccountId?: string | null;
  bankName?: string | null;
  accountName?: string | null;
  maskedAccount?: string | null;
  currentBalance?: number | null;
  currency?: string | null;
  connectedAt?: string | null;
  lastSyncedAt?: string | null;
  lastError?: string | null;
  isActive?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bank-transactions".
 */
export interface BankTransaction {
  id: number;
  family: number | Family;
  bankConnection: number | BankConnection;
  transactionKey: string;
  externalTransactionId: string;
  direction: 'in' | 'out';
  amount: number;
  currency: string;
  bookingDate?: string | null;
  valueDate?: string | null;
  description?: string | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bank-transfers".
 */
export interface BankTransfer {
  id: number;
  family: number | Family;
  initiatedBy: number | Customer;
  initiatedByName: string;
  fromConnection: number | BankConnection;
  toConnection: number | BankConnection;
  amount: number;
  currency: string;
  note?: string | null;
  status: 'completed' | 'failed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-events".
 */
export interface CalendarEvent {
  id: number;
  family: number | Family;
  child?: (number | null) | Child;
  title: string;
  eventType: 'handover' | 'pickup' | 'dropoff' | 'school' | 'activity' | 'medical' | 'payment' | 'other';
  priority?: ('normal' | 'important' | 'urgent') | null;
  location?: string | null;
  notes?: string | null;
  requiresConfirmation?: boolean | null;
  confirmationStatus?: ('not-required' | 'pending' | 'confirmed' | 'declined') | null;
  confirmedAt?: string | null;
  confirmedBy?: (number | null) | Customer;
  handoverFrom?: (number | null) | Customer;
  handoverTo?: (number | null) | Customer;
  responsibleParent?: (number | null) | Customer;
  handoverStatus?: ('not-started' | 'delivered' | 'completed') | null;
  handoverDeliveredAt?: string | null;
  handoverDeliveredBy?: (number | null) | Customer;
  handoverReceivedAt?: string | null;
  handoverReceivedBy?: (number | null) | Customer;
  linkedEconomyTransaction?: (number | null) | EconomyTransaction;
  source: 'manual' | 'economy-transaction' | 'economy-request' | 'system';
  silentSync?: boolean | null;
  startAt: string;
  endAt: string;
  allDay?: boolean | null;
  createdBy?: (number | null) | Customer;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'landingPage';
        value: number | LandingPage;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'aboutPage';
        value: number | AboutPage;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'families';
        value: number | Family;
      } | null)
    | ({
        relationTo: 'children';
        value: number | Child;
      } | null)
    | ({
        relationTo: 'child_documents';
        value: number | ChildDocument;
      } | null)
    | ({
        relationTo: 'audit_logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'economy-transactions';
        value: number | EconomyTransaction;
      } | null)
    | ({
        relationTo: 'bank-connections';
        value: number | BankConnection;
      } | null)
    | ({
        relationTo: 'bank-transactions';
        value: number | BankTransaction;
      } | null)
    | ({
        relationTo: 'bank-transfers';
        value: number | BankTransfer;
      } | null)
    | ({
        relationTo: 'calendar-events';
        value: number | CalendarEvent;
      } | null)
    | ({
        relationTo: 'economy-requests';
        value: number | EconomyRequest;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landingPage_select".
 */
export interface LandingPageSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        description?: T;
        image?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              url?: T;
            };
        secondaryCTA?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  about?:
    | T
    | {
        title?: T;
        content?: T;
        utfordringer?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        prinsipper?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  howItWorks?:
    | T
    | {
        title?: T;
        steps?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  features?:
    | T
    | {
        title?: T;
        intro?: T;
        image?: T;
        items?:
          | T
          | {
              featureTitle?: T;
              description?: T;
              id?: T;
            };
      };
  whySamsam?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        reasons?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  finalCTA?:
    | T
    | {
        title?: T;
        description?: T;
        primaryButton?:
          | T
          | {
              label?: T;
              url?: T;
            };
        secondaryButton?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  family?: T;
  author?: T;
  authorName?: T;
  type?: T;
  child?: T;
  title?: T;
  content?: T;
  important?: T;
  attachments?: T;
  likes?: T;
  comments?:
    | T
    | {
        author?: T;
        authorName?: T;
        content?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
      };
  intro?:
    | T
    | {
        title?: T;
        content?: T;
      };
  missionVision?:
    | T
    | {
        missionTitle?: T;
        missionText?: T;
        visionTitle?: T;
        visionText?: T;
      };
  values?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  story?:
    | T
    | {
        title?: T;
        content?: T;
      };
  commitment?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        title?: T;
        text?: T;
        button?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  birthDate?: T;
  phone?: T;
  address?: T;
  gender?: T;
  familyRole?: T;
  avatar?: T;
  family?: T;
  language?: T;
  notificationsEnabled?: T;
  notifyCalendarChanges?: T;
  notifyExpenseUpdates?: T;
  notifyStatusUpdates?: T;
  notifyDocumentUpdates?: T;
  sharePhoneWithFamily?: T;
  shareAddressWithFamily?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "families_select".
 */
export interface FamiliesSelect<T extends boolean = true> {
  name?: T;
  inviteCode?: T;
  members?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "children_select".
 */
export interface ChildrenSelect<T extends boolean = true> {
  family?: T;
  fullName?: T;
  birthDate?: T;
  gender?: T;
  avatar?: T;
  nationalId?: T;
  medical?:
    | T
    | {
        bloodType?: T;
        allergies?:
          | T
          | {
              value?: T;
              id?: T;
            };
        conditions?:
          | T
          | {
              value?: T;
              id?: T;
            };
        notesShort?: T;
        gp?:
          | T
          | {
              name?: T;
              clinic?: T;
              phones?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
            };
      };
  school?:
    | T
    | {
        schoolName?: T;
        className?: T;
        mainTeacher?: T;
      };
  emergencyContacts?:
    | T
    | {
        name?: T;
        relation?: T;
        isPrimary?: T;
        phones?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  profileStatus?: T;
  profileStatusReason?: T;
  profileStatusChangedBy?: T;
  profileStatusChangedAt?: T;
  status?: T;
  createdBy?: T;
  lastEditedBy?: T;
  confirmedBy?: T;
  confirmedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "child_documents_select".
 */
export interface ChildDocumentsSelect<T extends boolean = true> {
  family?: T;
  child?: T;
  file?: T;
  title?: T;
  category?: T;
  noteShort?: T;
  uploadedBy?: T;
  uploadedByName?: T;
  version?: T;
  replaces?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit_logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  family?: T;
  child?: T;
  childNameSnapshot?: T;
  actorId?: T;
  actorType?: T;
  actorRole?: T;
  relatedToRole?: T;
  actorName?: T;
  action?: T;
  entityType?: T;
  scope?: T;
  severity?: T;
  visibleInFamilyTimeline?: T;
  entityId?: T;
  targetLabel?: T;
  summary?: T;
  changes?:
    | T
    | {
        field?: T;
        from?: T;
        to?: T;
        id?: T;
      };
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  family?: T;
  child?: T;
  type?: T;
  event?: T;
  title?: T;
  message?: T;
  link?: T;
  isRead?: T;
  readAt?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "economy-transactions_select".
 */
export interface EconomyTransactionsSelect<T extends boolean = true> {
  family?: T;
  createdBy?: T;
  paidBy?: T;
  child?: T;
  title?: T;
  description?: T;
  type?: T;
  category?: T;
  amount?: T;
  currency?: T;
  status?: T;
  transactionDate?: T;
  sourceType?: T;
  requestRef?: T;
  requestCreatedByName?: T;
  approvedByName?: T;
  paidFromScope?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bank-connections_select".
 */
export interface BankConnectionsSelect<T extends boolean = true> {
  family?: T;
  connectionScope?: T;
  ownerCustomer?: T;
  provider?: T;
  status?: T;
  state?: T;
  externalSessionId?: T;
  externalAccountId?: T;
  bankName?: T;
  accountName?: T;
  maskedAccount?: T;
  currentBalance?: T;
  currency?: T;
  connectedAt?: T;
  lastSyncedAt?: T;
  lastError?: T;
  isActive?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bank-transactions_select".
 */
export interface BankTransactionsSelect<T extends boolean = true> {
  family?: T;
  bankConnection?: T;
  transactionKey?: T;
  externalTransactionId?: T;
  direction?: T;
  amount?: T;
  currency?: T;
  bookingDate?: T;
  valueDate?: T;
  description?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bank-transfers_select".
 */
export interface BankTransfersSelect<T extends boolean = true> {
  family?: T;
  initiatedBy?: T;
  initiatedByName?: T;
  fromConnection?: T;
  toConnection?: T;
  amount?: T;
  currency?: T;
  note?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-events_select".
 */
export interface CalendarEventsSelect<T extends boolean = true> {
  family?: T;
  child?: T;
  title?: T;
  eventType?: T;
  priority?: T;
  location?: T;
  notes?: T;
  requiresConfirmation?: T;
  confirmationStatus?: T;
  confirmedAt?: T;
  confirmedBy?: T;
  handoverFrom?: T;
  handoverTo?: T;
  responsibleParent?: T;
  handoverStatus?: T;
  handoverDeliveredAt?: T;
  handoverDeliveredBy?: T;
  handoverReceivedAt?: T;
  handoverReceivedBy?: T;
  linkedEconomyTransaction?: T;
  source?: T;
  silentSync?: T;
  startAt?: T;
  endAt?: T;
  allDay?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "economy-requests_select".
 */
export interface EconomyRequestsSelect<T extends boolean = true> {
  family?: T;
  createdBy?: T;
  createdByName?: T;
  child?: T;
  title?: T;
  amount?: T;
  category?: T;
  notes?: T;
  status?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  decisionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}